# Test with Salsa CI full Debian build and more
# Also test reverse deps with prototype from
# https://salsa.debian.org/salsa-ci-team/pipeline/-/merge_requests/613
---
include:
  - https://salsa.debian.org/aquilamacedo/pipeline/raw/testing-ratt-based-in-santiago-implementation/salsa-ci.yml
  - https://salsa.debian.org/aquilamacedo/pipeline/raw/testing-ratt-based-in-santiago-implementation/pipeline-jobs.yml
variables:
  SALSA_CI_ENABLE_BUILD_REVERSE_DEPENDENCIES: 1

